CREATE DATABASE BookVerse_DB;

USE BookVerse_DB;

-- Books table

CREATE TABLE Books
(
    Book_ID INT PRIMARY KEY,
    Title VARCHAR(250) NOT NULL,
    Author VARCHAR(150) NOT NULL,
    Genre VARCHAR(80),Published_Year YEAR,
    Price DECIMAL(10,2),
    Stock INT
);

-- Customers table

CREATE TABLE Customers
(
    Customer_ID INT PRIMARY KEY,
    Name VARCHAR(120),
    Email VARCHAR(150) UNIQUE,
    Phone VARCHAR(20),
    City VARCHAR(100),
    Country VARCHAR(100)
);

-- Orders table

CREATE TABLE Orders
(
    Order_ID INT PRIMARY KEY,
    Customer_ID INT,
    Book_ID INT,
    Order_Date DATE,
    Quantity INT,
    Total_Amount DECIMAL(10,2),
    CONSTRAINT FK_Order_Customer
        FOREIGN KEY(Customer_ID)
        REFERENCES Customers(Customer_ID),
    CONSTRAINT FK_Order_Book
        FOREIGN KEY(Book_ID)
		REFERENCES Books(Book_ID)
);

-- BOOKS TABLE
select count(*)
from books;
SELECT COUNT(DISTINCT Book_ID)
FROM books;
-- no.of records are 496. which are distinct.
SELECT MIN(Book_ID), MAX(Book_ID)
FROM books;

-- null values in columns
SELECT COUNT(*)
FROM books
WHERE Title IS NULL;
SELECT COUNT(*)
FROM books
WHERE Author IS NULL;
SELECT COUNT(*)
FROM books
WHERE Genre IS NULL;
SELECT COUNT(*)
FROM books
WHERE Published_Year IS NULL;
SELECT COUNT(*)
FROM books
WHERE Price IS NULL;
SELECT COUNT(*)
FROM books
WHERE Stock IS NULL;
-- this books table have no null values in Title, Author, Genre, Published_Year, Price and Stock columns.

-- Duplicate records
SELECT Title, Author, Genre, Published_Year, Price, Stock
FROM books
GROUP BY Title, Author, Genre, Published_Year, Price, Stock
HAVING COUNT(*) > 1;
-- no duplicate records in the table.

-- column datatypes
desc books;

WITH RECURSIVE numbers AS (
    SELECT 1 AS num
    UNION ALL
    SELECT num + 1
    FROM numbers
    WHERE num < 500
)
SELECT num AS Missing_Book_ID
FROM numbers
WHERE num NOT IN (SELECT Book_ID FROM books);

-- CUSTOMERS TABLE
select count(*)
from customers;
SELECT COUNT(DISTINCT customer_id)
FROM customers;
-- there are 500 records in Customers Table

-- null values in columns
SELECT COUNT(*)
FROM customers
WHERE customer_id IS NULL;
SELECT COUNT(*)
FROM customers
WHERE name IS NULL;
SELECT COUNT(*)
FROM customers
WHERE email IS NULL;
SELECT COUNT(*)
FROM customers
WHERE phone IS NULL;
SELECT COUNT(*)
FROM customers
WHERE city IS NULL;
SELECT COUNT(*)
FROM customers
WHERE country IS NULL;
-- no null value in any of the columns

-- Duplicate records
SELECT customer_id, name, email, phone, city, country
FROM customers
GROUP BY customer_id, name, email, phone, city, country
HAVING COUNT(*) > 1;
-- no duplicate records in the customers table

-- column datatypes
desc customers;

-- ORDERS TABLE
select count(*)
from orders;
SELECT COUNT(DISTINCT order_id)
FROM orders;
-- total records from Orders table are 495

-- null values in columns
SELECT COUNT(*)
FROM orders
WHERE order_id IS NULL;
SELECT COUNT(*)
FROM orders
WHERE customer_id IS NULL;
SELECT COUNT(*)
FROM orders
WHERE book_id IS NULL;
SELECT COUNT(*)
FROM orders
WHERE order_date IS NULL;
SELECT COUNT(*)
FROM orders
WHERE quantity IS NULL;
SELECT COUNT(*)
FROM orders
WHERE total_amount IS NULL;
-- no null values in any of the ccolumns in orders table

-- duplicate records
SELECT order_id, customer_id, book_id, order_date, quantity, total_amount
FROM orders
GROUP BY order_id, customer_id, book_id, order_date, quantity, total_amount
HAVING COUNT(*) > 1;
-- no duplicate records in orders table
-- column datatypes 
desc orders;


-- foreign-key validation
-- Show me the Customer_ID from Orders where there is no matching Customer_ID in Customers.
select o.customer_id from orders o
left join customers c
on o.customer_id = c.customer_id
where c.customer_id is null;
-- Does every Book_ID in Orders exist in Books
select o.customer_id from orders o
left join books b
on o.book_id = b.book_id
where b.book_id is null;

-- BASIC DATA EXPLORATION
-- What is the total number of books in BookVerse?
select count(*) from books;
-- How many customers are there in BookVerse?
select count(*) from customers;
-- How many orders are there in BookVerse?
select count(*) from orders;
-- How many different countries are represented among the customers?
select count(distinct country) from customers;
-- What are the different genres available in BookVerse?
select distinct genre from books;
-- What is the total quantity of books sold?
select sum(quantity) from orders;
-- What is the total revenue generated by BookVerse?
select sum(total_amount) from orders;
-- What is the average order value?
select avg(total_amount) from orders;
-- What is the minimum order value?
select min(total_amount) from orders;
-- What is the maximum order value?
select max(total_amount) from orders;
-- What is the average quantity of books purchased per order?
select avg(quantity) from orders;
-- What is the average book price?
select avg(price) from books;
-- What is the cheapest book price?
select min(price) from books;
-- What is the most expensive book price?
select max(price) from books;
-- How many books are available in each genre?
select genre,count(*) from books group by genre;
-- What is the total revenue generated for each genre?
select b.genre,sum(o.total_amount) from books b join orders o on b.book_id = o.book_id group by genre;
-- Which genre has the highest total revenue?
SELECT b.genre, SUM(o.total_amount) as total_rev
FROM books b
JOIN orders o
ON b.book_id = o.book_id
GROUP BY b.genre
ORDER BY total_rev DESC
LIMIT 1;
-- Which book has generated the highest total revenue?
select b.book_id,b.title,sum(o.total_amount) as tot_rev from books b 
join orders o 
on b.book_id = o.book_id 
group by b.book_id,b.title
order by tot_rev desc 
limit 1;
-- Which customer has spent the most money?
select c.customer_id,sum(o.total_amount) as high_amount from customers c
join orders o
on c.customer_id = o.customer_id
group by c.customer_id
order by high_amount desc
limit 1;
-- Which country has the highest number of customers?
select country,sum(customer_id) as noof_customers from customers 
group by country
order by noof_customers desc
limit 1;
-- Find the total revenue generated by each customer, but display only customers whose total spending is greater than 10,000.
select c.customer_id,sum(o.total_amount) as tot_rev from customers c
join orders o
on c.customer_id = o.customer_id
group by c.customer_id
having tot_rev>10000;
-- Find the genres whose average book price is greater than the overall average book price.
select genre,avg(price) as avg_price from books group by genre having avg_price > (select avg(price) from books);
-- Find the top 3 customers based on their total spending.
select c.customer_id,sum(o.total_amount) as high_amount from customers c
join orders o
on c.customer_id = o.customer_id
group by c.customer_id
order by high_amount desc
limit 3;
-- Find the month that generated the highest total revenue.
select month(order_date) as month_number,sum(total_amount) as tot_rev from orders 
group by month(order_date) 
order by tot_rev desc
limit 1;
-- Find the top 5 best-selling books based on the total quantity sold.
select b.book_id,b.title,sum(o.quantity) as tot_quantity from books b
join orders o on b.book_id = o.book_id
group by b.book_id,b.title
order by tot_ desc
limit 5;


-- BOOK VERSE BUSINESS ANALYSIS

-- Understand Sales Performance
-- Q1. Which 5 books generate the highest revenue?
select b.book_id,b.title,sum(o.total_amount) as total_revenue from books b
join orders o on b.book_id = o.book_id
group by b.book_id,b.title
order by total_revenue desc
limit 5;
	-- Integrated secondary access is the book which generate highest revenue.
    -- These books are the major revenue contributors to BookVerse and should receive more attention in promotions.
-- Q2. Which 5 books have the highest quantity sold?
select b.book_id,b.title,sum(o.quantity) as tot_quantity from books b
join orders o on b.book_id = o.book_id
group by b.book_id,b.title
order by tot_quantity desc
limit 5;
	-- Realigned multi-tasking installation is the book which is sold more.
    -- These are the most popular books based on the number of units sold.
-- Q3. Which genres generate the highest revenue?
select b.genre, sum(o.total_amount) as total_rev from books b
join orders o
on b.book_id = o.book_id
group by b.genre
order by total_rev desc
limit 5;
	-- Romance is the genre that is generating highest revenue.
    -- The top-performing genres contribute the most to overall sales and could be prioritized for future promotions.
-- Q4. Which authors generate the highest revenue?
select b.author, sum(o.total_amount) as total_rev from books b
join orders o
on b.book_id = o.book_id
group by b.author
order by total_rev desc
limit 5;
	-- Sheena Harris generates the highest revenue.

-- Understand Customer Purchasing Behaviour
-- Q1. Which customers have placed the most orders?
select c.customer_id,count(o.order_id) as tot_orders from customers c
join orders o
on c.customer_id = o.customer_id
group by c.customer_id
order by tot_orders desc
limit 5;
	-- 364 customer have ordered more.
	-- These customers are the most active customers because they have placed more orders than others.
-- Q2. Which customers have spent the most money?
select c.customer_id,sum(o.total_amount) as high_amount from customers c
join orders o
on c.customer_id = o.customer_id
group by c.customer_id
order by high_amount desc
limit 5;
	-- These customers contribute significantly to the company's revenue through their higher spending.
-- Q3. Which countries have the highest number of customers/orders?
select country,sum(customer_id) as noof_customers from customers 
group by country
order by noof_customers desc
limit 5;
	-- Countries with higher customer activity represent stronger markets for BookVerse.
-- Q4. Which customers have purchased more than once?
select customer_id,count(order_id) as total_orders
from orders
group by customer_id
having COUNT(order_id) > 1
order by total_orders desc;

-- Understand Product & Genre Performance
-- Q1. Which books have the highest sales quantity?
select b.book_id,b.title,sum(o.quantity) as sale_quantity from books b
join orders o
on b.book_id = o.book_id
group by b.book_id
order by sale_quantity desc
limit 5;
	-- These books have strong customer demand based on units sold.
-- Q2. Which genres have the highest sales volume?
select b.genre,sum(o.quantity) as sale_quantity from books b
join orders o
on b.book_id = o.book_id
group by b.genre
order by sale_quantity desc
limit 3;
	-- These genres have stronger demand in terms of the number of books purchase.
-- Q3. Which books have low sales?
select b.genre,sum(o.quantity) as sale_quantity from books b
join orders o
on b.book_id = o.book_id
group by b.genre
order by sale_quantity
limit 3;
	-- These books have relatively weak sales and may require promotional attention.
-- Q4. Which books have never been ordered?
select b.book_id, b.title
from books b
left join orders o
on b.book_id = o.book_id
where o.book_id is null;
	-- These books have no recorded sales and may need promotion or further evaluation.
    
-- Understand Inventory Position
-- Q1. Which books currently have low stock?
select book_id, title, stock
from books
where stock < 10
order by stock asc;
	-- These books have limited stock remaining and may require attention before the next procurement cycle.
-- Q2. Which genres have the highest inventory?
select genre, sum(stock) as total_stock
from books
group by  genre
order by total_stock desc;
	-- These genres have the largest amount of stock currently available.
-- Q3. Which books have high stock but low sales?
select b.book_id, b.title, b.stock, sum(o.quantity) AS total_sold from books b
join orders o
on b.book_id = o.book_id
group by b.book_id, b.title, b.stock
having b.stock > 20 and sum(o.quantity) < 10
order by b.stock desc
limit 5;
	-- These books have relatively high inventory but are selling slowly, which may indicate excess stock.
-- Q4. Which books have high sales but low stock?
select b.book_id, b.title, b.stock
from books b
left join orders o
on b.book_id = o.book_id
where o.book_id is null
limit 5;
-- These books are currently in the inventory but have no recorded orders.

-- Sales & Inventory Opportunities
-- Q1. Which high-selling books currently have low stock?
select b.book_id, b.title,sum(o.quantity) as total_sold,b.stock from books b
join orders o
on b.book_id = o.book_id
group by b.book_id, b.title, b.stock
having sum(o.quantity) > 10 and b.stock < 20
order by total_sold desc;
	-- These books have strong demand but limited stock, creating a risk of stock shortage.
-- Q2. which books have high stock but low sales?
select b.book_id, b.title,b.stock,sum(o.quantity) as total_sold from books b
join orders o
on b.book_id = o.book_id
group by b.book_id, b.title, b.stock
having b.stock > 20 and sum(o.quantity) < 10
order by b.stock desc;
	-- These books have a large amount of inventory but are not selling well.
-- Q3. which genres have high sales but low inventory?
select b.genre,sum(o.quantity) as total_sold,sum(b.stock) as total_stock from books b
join orders o
on b.book_id = o.book_id
group by b.genre
having sum(o.quantity) > 20 and sum(b.stock) < 100
order by total_sold desc;
	-- These genres have strong demand but relatively limited inventory.
-- Q4. which books have never been ordered?
select b.book_id, b.title, b.genre, b.stock from books b
left join orders o
on b.book_id = o.book_id
where o.book_id is null
order by b.stock desc;
	-- These books have not generated any sales despite being available in the inventory.

# Business Recommendations

###  Sales Performance

-- * Top 5 revenue books: Integrated secondary access (₹1,104.69), Multi-tiered responsive parallelism (₹1,077.12), and Switchable modular moratorium (₹1,047.48) are the top revenue contributors.
	-- → Maintain sufficient stock and prioritize these books in promotions.

-- * Top-selling books: Books with the highest quantity sold indicate strong demand.
	-- → Prioritize replenishment to avoid stock-outs.

-- * Top-performing genres: High-revenue genres contribute strongly to overall sales.
	-- → Increase marketing focus and maintain adequate inventory for these genres.

###  Customer Purchasing Behaviour

-- * Most active customers: Customers with the highest order counts are frequent buyers.
	--  → Introduce loyalty rewards and repeat-purchase offers.

-- * Highest-spending customers: High-spending customers contribute significantly to revenue.
	-- → Focus on customer retention through personalized offers and loyalty benefits.

-- * High-activity countries: Countries with the highest customer activity represent important markets.
	-- → Target these locations with focused marketing campaigns.

###  Product & Genre Performance

-- * High-quantity books: Strong-selling books indicate high customer demand.
	-- → Maintain higher stock levels for these products.

-- * High-volume genres: Popular genres have stronger demand.
	-- → Maintain wider product selection in these genres.

-- * Low-selling books: Books with weak sales may require additional attention.
	-- → Use discounts or promotions to improve sales before reducing inventory.

-- * Never-ordered books: Books with zero orders are not currently generating sales.
	-- → Promote them or review whether they should be stocked in future.

###  Inventory Position

-- * Low-stock books: Limited inventory can create stock-out risks.
	-- → Replenish low-stock books, especially those with strong sales.

-- * High-inventory genres: Large inventory levels require monitoring.
	-- → Compare inventory with sales before purchasing additional stock.

-- * High-stock, low-sales books: These products may represent excess inventory.
	-- → Use discounts, bundles, or promotions to clear stock.

-- * Never-ordered books: Zero-sales products may become dead stock.
	-- → Review their demand and consider reducing future procurement.

###  Sales & Inventory Opportunities

-- * High sales + low stock: Strong demand with limited availability.
	-- → Priority: Replenish immediately.

-- * High stock + low sales: Excess inventory with weak demand.
	-- → Priority: Promote through discounts or bundles.

-- * High-sales genre + low inventory: Demand may exceed current availability.
	-- → Increase inventory for these genres.

-- * No orders: Products are not generating sales.
	-- → Promote, review, or reduce future procurement.
